### ISSUE TITLE
cannot build docker image

### ISSUE THREAD

**Issue by cedcoul** [rwk-unil/xSqueezeIt#1]
You need to change ubuntu base image from 21.04 to 20.04 which is LTS

Alternatively, if you use the last version of ubuntu, you cannot compile htslib with this message:
configure: error: cannot find required auxiliary files: config.guess config.sub

**Comment by rwk-unil** [comment]
Hello.
Thank you for pointing this out. I updated the Dockerfile to use Ubuntu 20.04 LTS which is indeed a good idea.


As for compiling HTSLIB on the latest version of Ubuntu, I don't know I did try it out yet. I don't think there is a need for the latest version of ubuntu to run xsqueezit through a Docker. If at some point there is a good reason/need to update it I'll look into it.

However, if you need to compile HTSLIB on the latest Ubuntu, it might be better to raise the issue on the HTSLIB repository.

Best regards.
Rick
